// fitundfun/pages/lager.vue
<script setup lang="ts">
import { Download, ExternalLink, Calendar, MapPin } from 'lucide-vue-next'

useHead({
  title: 'Aktuelles Lager - Fit & Fun',
})

const client = useSupabaseClient()

// Fetch aktuelles Lager
const { data: lager } = await useAsyncData('lager-aktuell', async () => {
  const { data } = await client
    .from('lager')
    .select('*')
    .eq('ist_aktuell', true)
    .single()
  return data
})

// Fetch Downloads für aktuelles Lager
const { data: downloads } = await useAsyncData('lager-downloads', async () => {
  if (!lager.value?.id) return []
  const { data } = await client
    .from('lager_downloads')
    .select('*')
    .eq('lager_id', lager.value.id)
    .order('reihenfolge')
  return data || []
})

const { formatDate } = useFormat()

const { getPublicUrl } = useStorageUrl()

const getDownloadUrl = (filePath: string) => {
  return getPublicUrl('pdfs', filePath)
}
</script>

<template>
  <div class="container mx-auto px-4 py-12">
    <!-- Header -->
    <div class="max-w-4xl mx-auto mb-12 text-center">
      <h1 class="text-4xl font-bold text-slate-900 mb-4">
        Lager {{ lager?.jahr || new Date().getFullYear() }}
      </h1>

      <div v-if="lager" class="flex flex-wrap justify-center gap-6 text-slate-600">
        <div class="flex items-center gap-2">
          <Calendar class="w-5 h-5 text-primary-600" />
          <span>{{ formatDate(lager.datum_von) }} - {{ formatDate(lager.datum_bis) }}</span>
        </div>
        <div class="flex items-center gap-2">
          <MapPin class="w-5 h-5 text-primary-600" />
          <span>Brigels, Crestneder</span>
        </div>
      </div>
    </div>

    <div v-if="lager" class="max-w-4xl mx-auto">
      <!-- Beschreibung -->
      <div v-if="lager.beschreibung" class="bg-white rounded-xl p-6 shadow-sm border border-slate-200 mb-8">
        <p class="text-slate-700 leading-relaxed whitespace-pre-line">{{ lager.beschreibung }}</p>
      </div>

      <!-- Preis -->
      <div v-if="lager.preis" class="bg-primary-50 rounded-xl p-6 border border-primary-200 mb-8">
        <p class="text-primary-800 font-semibold">
          Preis: {{ lager.preis }}
        </p>
      </div>

      <!-- Downloads -->
      <div v-if="downloads && downloads.length > 0" class="mb-8">
        <h2 class="text-2xl font-semibold text-slate-900 mb-6">Downloads</h2>
        <div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <a
            v-for="download in downloads"
            :key="download.id"
            :href="getDownloadUrl(download.file_path)"
            target="_blank"
            class="flex items-center gap-3 bg-white rounded-lg p-4 border border-slate-200 hover:border-orange-300 hover:shadow-md transition-all group"
          >
            <div class="p-2 bg-orange-100 rounded-lg group-hover:bg-orange-200 transition-colors">
              <Download class="w-5 h-5 text-orange-600" />
            </div>
            <span class="font-medium text-slate-700 group-hover:text-orange-600 transition-colors">
              {{ download.titel }}
            </span>
          </a>
        </div>
      </div>

      <!-- Fotoalbum Link -->
      <div v-if="lager.immich_album_url" class="bg-gradient-to-r from-primary-600 to-primary-700 rounded-xl p-6 text-white">
        <h2 class="text-xl font-semibold mb-2">Fotoalbum</h2>
        <p class="text-primary-100 mb-4">Alle Fotos vom Lager ansehen, herunterladen und eigene hochladen.</p>
        <a
          :href="lager.immich_album_url"
          target="_blank"
          rel="noopener"
          class="inline-flex items-center gap-2 bg-white text-primary-700 px-6 py-3 rounded-lg font-semibold hover:bg-primary-50 transition-colors"
        >
          Zum Fotoalbum
          <ExternalLink class="w-4 h-4" />
        </a>
      </div>
    </div>

    <!-- Kein Lager -->
    <div v-else class="max-w-2xl mx-auto text-center py-12">
      <p class="text-slate-600 text-lg">
        Informationen zum nächsten Lager werden bald veröffentlicht.
      </p>
      <NuxtLink to="/kontakt" class="inline-block mt-4 text-primary-600 hover:text-primary-700 font-medium">
        Bei Fragen kontaktiere uns →
      </NuxtLink>
    </div>
  </div>
</template>

// src/app/lager/page.tsx
import Link from "next/link";
import {
  ArrowUpRight,
  CalendarDays,
  Play,
  UsersRound,
} from "lucide-react";
import { getLager } from "@/lib/data";
import { formatDateRange } from "@/lib/utils";
import { richTextToPlainText } from "@/lib/sanitize";
import type { LagerRecord } from "@/lib/pb-types";

export const revalidate = 300;

export const metadata = {
  title: "Lager-Archiv",
  description: "Alle fit&fun Familienlager in Brigels seit 2007.",
};

export default async function ArchivPage() {
  const lager = await getLager();
  const aktuelleLager = lager.filter((eintrag) => eintrag.status === "veroeffentlicht");
  const vergangeneLager = lager.filter((eintrag) => eintrag.status === "archiviert");
  const erstesJahr = vergangeneLager.at(-1)?.jahr || aktuelleLager.at(-1)?.jahr;
  const letztesJahr = aktuelleLager[0]?.jahr || vergangeneLager[0]?.jahr;

  return (
    <main className="bg-sand">
      <div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8">
        <header className="max-w-3xl">
          <p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">
            {erstesJahr && letztesJahr ? `${erstesJahr} – ${letztesJahr}` : "Archiv"}
          </p>
          <h1 className="camp-display mt-4 text-4xl leading-none text-ink sm:text-6xl">
            Alle Lagerjahre
          </h1>
          <p className="mt-5 max-w-2xl text-base font-semibold leading-relaxed text-muted">
            Termine, Programme, Dokumente und Erinnerungen aus fast zwei Jahrzehnten
            fit&amp;fun in Brigels.
          </p>
        </header>

        {aktuelleLager.length > 0 ? (
          <section className="mt-12 sm:mt-16">
            <div className="mb-5 flex items-end justify-between gap-4">
              <h2 className="font-display text-xl uppercase text-ink">Aktuelles Lager</h2>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {aktuelleLager.map((eintrag) => (
                <CurrentCampCard key={eintrag.id} lager={eintrag} />
              ))}
            </div>
          </section>
        ) : null}

        {vergangeneLager.length > 0 ? (
          <section className="mt-16 sm:mt-20">
            <div className="mb-6 flex items-end justify-between gap-4">
              <div>
                <p className="text-xs font-bold uppercase tracking-[0.18em] text-muted">
                  Rückblick
                </p>
                <h2 className="camp-display mt-2 text-3xl text-ink sm:text-4xl">
                  Vergangene Lager
                </h2>
              </div>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              {vergangeneLager.map((eintrag) => (
                <ArchivedCampCard key={eintrag.id} lager={eintrag} />
              ))}
            </div>
          </section>
        ) : null}

        {aktuelleLager.length === 0 && vergangeneLager.length === 0 ? (
          <p className="mt-12 text-sm text-muted">
            Noch keine Lager veröffentlicht.
          </p>
        ) : null}
      </div>
    </main>
  );
}

function CurrentCampCard({ lager }: { lager: LagerRecord }) {
  return (
    <Link
      href={`/lager/${lager.jahr}`}
      className="group flex min-h-52 flex-col justify-between rounded-[1.75rem] bg-ink p-6 text-white transition-transform hover:-translate-y-1 sm:p-7"
    >
      <div className="flex items-start justify-between gap-4">
        <span className="camp-display text-5xl leading-none">{lager.jahr}</span>
        <ArrowUpRight className="size-5 text-accent-light transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
      </div>
      <div>
        <span className="inline-flex items-center gap-2 text-sm font-semibold text-white/75">
          <CalendarDays className="size-4 text-accent-light" />
          {formatDateRange(lager.datum_von, lager.datum_bis)}
        </span>
        <p className="mt-3 text-sm leading-relaxed text-white/60">
          Alle Informationen und Dokumente zum nächsten Lager.
        </p>
      </div>
    </Link>
  );
}

function ArchivedCampCard({ lager }: { lager: LagerRecord }) {
  const zeitraum =
    lager.datum_von && lager.datum_bis
      ? formatDateRange(lager.datum_von, lager.datum_bis)
      : null;

  return (
    <Link
      href={`/lager/${lager.jahr}`}
      className="group flex min-h-64 flex-col rounded-[1.75rem] border border-ink/10 bg-white p-6 transition hover:-translate-y-1 hover:border-ink/20 hover:shadow-[0_18px_45px_rgba(14,28,48,0.08)] sm:p-7"
    >
      <div className="flex items-start justify-between gap-4">
        <span className="camp-display text-4xl leading-none text-ink">{lager.jahr}</span>
        <ArrowUpRight className="size-5 text-muted transition-all group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-accent" />
      </div>

      <div className="mt-6 flex flex-wrap gap-x-4 gap-y-2 text-xs font-bold uppercase tracking-[0.12em] text-muted">
        {zeitraum ? (
          <span className="inline-flex items-center gap-1.5">
            <CalendarDays className="size-3.5" /> {zeitraum}
          </span>
        ) : null}
        {lager.teilnehmer ? (
          <span className="inline-flex items-center gap-1.5">
            <UsersRound className="size-3.5" /> {lager.teilnehmer}
          </span>
        ) : null}
      </div>

      <p className="mt-5 line-clamp-3 text-sm font-semibold leading-relaxed text-muted">
        {richTextToPlainText(lager.beschreibung || "") || "Dokumente und Erinnerungen aus diesem Lagerjahr."}
      </p>

      <div className="mt-auto flex items-center gap-3 pt-6 text-xs font-bold text-ink/60">
        {lager.youtube_url ? (
          <span className="inline-flex items-center gap-1.5">
            <Play className="size-3.5" /> Video
          </span>
        ) : null}
        <span className="ml-auto text-accent">Details</span>
      </div>
    </Link>
  );
}
