// fitundfun-mern/client/src/components/AppHeader.tsx
import { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { Menu, X } from 'lucide-react';

const navItems = [
  { to: '/', label: 'Home' },
  { to: '/lager', label: 'Aktuelles Lager' },
  { to: '/archiv', label: 'Archiv' },
  { to: '/lagerhaus', label: 'Lagerhaus' },
  { to: '/sponsoren', label: 'Sponsoren' },
  { to: '/kontakt', label: 'Kontakt' },
];

export default function AppHeader() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const toggleMobileMenu = () => setMobileMenuOpen((prev) => !prev);
  const closeMobileMenu = () => setMobileMenuOpen(false);

  return (
    <header className="sticky top-0 z-50 bg-white/95 backdrop-blur border-b border-slate-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <Link to="/" className="text-xl font-bold text-primary-700 hover:text-primary-800 transition-colors">
            Fit &amp; Fun
          </Link>

          {/* Desktop Navigation */}
          <nav className="hidden md:flex items-center space-x-1">
            {navItems.map((item) => (
              <NavLink
                key={item.to}
                to={item.to}
                end={item.to === '/'}
                className={({ isActive }) =>
                  `px-3 py-2 rounded-md text-sm font-medium transition-colors ${
                    isActive
                      ? 'text-primary-700 bg-primary-50'
                      : 'text-slate-600 hover:text-primary-700 hover:bg-slate-50'
                  }`
                }
              >
                {item.label}
              </NavLink>
            ))}
          </nav>

          {/* Mobile Menu Button */}
          <button
            type="button"
            className="md:hidden inline-flex items-center justify-center p-2 rounded-md text-slate-600 hover:text-primary-700 hover:bg-slate-100 transition-colors"
            onClick={toggleMobileMenu}
            aria-label="Navigation öffnen"
          >
            {mobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
          </button>
        </div>
      </div>

      {/* Mobile Navigation */}
      {mobileMenuOpen && (
        <div className="md:hidden border-t border-slate-200 bg-white">
          <nav className="px-4 py-3 space-y-1">
            {navItems.map((item) => (
              <NavLink
                key={item.to}
                to={item.to}
                end={item.to === '/'}
                onClick={closeMobileMenu}
                className={({ isActive }) =>
                  `block px-3 py-2 rounded-md text-base font-medium transition-colors ${
                    isActive
                      ? 'text-primary-700 bg-primary-50'
                      : 'text-slate-600 hover:text-primary-700 hover:bg-slate-50'
                  }`
                }
              >
                {item.label}
              </NavLink>
            ))}
          </nav>
        </div>
      )}
    </header>
  );
}

// fitundfun/components/AppHeader.vue
<script setup lang="ts">
import { Menu, X } from 'lucide-vue-next'

const isMenuOpen = ref(false)

const navItems = [
  { label: 'Home', to: '/' },
  { label: 'Aktuelles Lager', to: '/lager' },
  { label: 'Archiv', to: '/archiv' },
  { label: 'Lagerhaus', to: '/lagerhaus' },
  { label: 'Sponsoren', to: '/sponsoren' },
  { label: 'Kontakt', to: '/kontakt' },
]

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value
}
</script>

<template>
  <header class="sticky top-0 z-50 bg-white/95 backdrop-blur border-b border-slate-200">
    <div class="container mx-auto px-4">
      <nav class="flex items-center justify-between h-16">
        <!-- Logo -->
        <NuxtLink to="/" class="flex items-center gap-2">
          <span class="text-xl font-bold text-primary-700">Fit & Fun</span>
        </NuxtLink>

        <!-- Desktop Navigation -->
        <ul class="hidden md:flex items-center gap-6">
          <li v-for="item in navItems" :key="item.to">
            <NuxtLink
              :to="item.to"
              class="text-slate-600 hover:text-primary-700 transition-colors font-medium"
              active-class="text-primary-700"
            >
              {{ item.label }}
            </NuxtLink>
          </li>
        </ul>

        <!-- Mobile Menu Button -->
        <button
          class="md:hidden p-2 text-slate-600 hover:text-primary-700"
          @click="toggleMenu"
          aria-label="Menu öffnen"
        >
          <Menu v-if="!isMenuOpen" class="w-6 h-6" />
          <X v-else class="w-6 h-6" />
        </button>
      </nav>

      <!-- Mobile Navigation -->
      <div
        v-show="isMenuOpen"
        class="md:hidden border-t border-slate-200 py-4"
      >
        <ul class="flex flex-col gap-2">
          <li v-for="item in navItems" :key="item.to">
            <NuxtLink
              :to="item.to"
              class="block py-3 px-4 text-slate-600 hover:text-primary-700 hover:bg-slate-50 rounded-lg transition-colors font-medium"
              active-class="text-primary-700 bg-slate-50"
              @click="isMenuOpen = false"
            >
              {{ item.label }}
            </NuxtLink>
          </li>
        </ul>
      </div>
    </div>
  </header>
</template>
